
## setup for phpList development

version: '3.5'

networks:
 default:
  ipam:
   driver: default
   config:
   - subnet: 172.18.0.0/16

services:
   dbhost:
     container_name: phplist_dbhost
     image: phplist/testdata:medium
     volumes:
       - dbhost_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: phplist
     restart: always

   mailhog:
     container_name: phplist_mailhog
     image: mailhog/mailhog:latest
     ports:
       - 8025:8025
     environment:
       MH_SMTP_BIND_ADDR: 0.0.0.0:25

   phplist:
     container_name: phplist
     depends_on:
       - dbhost
       - mailhog
     image: phplist/phplist:${PHPLIST_VERSION:-latest}
     volumes:
       - ${CODE_PATH}:/var/www/phpList3
       - images:/var/www/phpList3/public_html/images
       - ${THEME_DEV_PATH}:/var/www/phpList3/public_html/lists/admin/ui/
       - ${PLUGIN_DEV_PATH}:/var/www/phpList3/public_html/lists/admin/plugins/
     ports:
       - "${PORT}:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: phplist
       DB_PASSWORD: phplist
       DB_NAME: phplistdb
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhog
   phpmyadmin:
       container_name: fsa-phpmyadmin
       image: phpmyadmin
       restart: always
       ports:
            - 8888:80
       environment:
            PMA_HOST: dbhost
       depends_on:
            - dbhost

volumes:
    images:
    dbhost_data:
